@api = http://localhost:3000/servicio

###

GET {{api}} HTTP/1.1

###

GET {{api}}/2 HTTP/1.1

###

GET {{api}}/count HTTP/1.1

###

POST {{api}} HTTP/1.1
Content-Type: application/json

{
    "fecha_solicitud": "12-06-2021",
    "hora_solicitud": "2021-06-13T23:02:00.000Z",
    "direccion_usuario": "Lago Villarrica 650",
    "duracion_paseo": "30 minutos",
    "mascota": "Django",
    "tiposervicio": 1
}

### 

PUT {{api}}/3 HTTP/1.1
Content-Type: application/json

{
    "fecha_solicitud": "2021-06-13",
    "hora_solicitud": "2021-06-13T15:32:00.000Z",
    "direccion_usuario": "Lago Villarrica 650",
    "duracion_paseo": "1 hora",
    "mascota": "Django",
    "agregado": "Paseo exclusivo por la plaza",
    "tiposervicio": 1
}


####

DELETE {{api}}/2 HTTP/1.1
