### GET

@api = http://localhost:3000/usuario

###
@apic = http://localhost:3000/cuidador

GET {{api}}

### CREATE

POST {{api}}  HTTP/1.1
Content-Type: application/json

{
    "nombre_usuario": "Dana",
    "apellido_usuario": "Hidalgo",
    "clave_usuario": "dana",
    "rut": "20.360.8245",
    "correo_electronico": "dana@gmail.com",
    "direccion": "7 Poniente",
    "numero_cel": 954353291,
    "tipousuario": 1
}

### GET ID

GET {{api}}/5

### DELETE

DELETE {{api}}/7

### GET COUNT

GET {{api}}/count HTTP/1.1

### UPDATE

PUT {{api}}/11 HTTP/1.1
Content-Type: application/json

{
    "nombre_usuario": "Yoru",
    "rut": "15.235.5432",
    "correo_electronico": "yoru@valorant.com",
    "direccion": "atlantico",
    "numero_cel": "97653297"
}


###

PUT {{api}}/2 HTTP/1.1
Content-Type: application/json

{
    "nombre_usuario": "Dana",
    "clave_usuario": "password",
    "rut": "20.360.824-1",
    "correo_electronico": "dana@mail.com",
    "direccion": "7 Poniente",
    "numero_cel": 56971244743,
    "tipousuario": 1
}

###

POST {{apic}}  HTTP/1.1
Content-Type: application/json

{
    "nombre_usuario": "Tobías",
    "clave_usuario": "password",
    "rut": "29.456.987-4",
    "correo_electronico": "toby@mail.com",
    "direccion": "3 Oriente",
    "numero_cel": 56971534643,
    "tipousuario": 2
}


###

GET {{api}}/3 HTTP/1.1
Content-Type: application/json

{
    "nombre_usuario": "Tobías",
    "tipousuario": 2
}