### GET

@api = http://localhost:3000/usuario

GET {{api}}

### CREATE

POST {{api}}  HTTP/1.1
Content-Type: application/json

{
    "nombre_usuario": "dana",
    "rut": "20.360.8245",
    "correo_electronico": "dana@gmail.com"
}

### GET ID

GET {{api}}/5

### DELETE

DELETE {{api}}/7

### GET COUNT

GET {{api}}/count HTTP/1.1

### UPDATE

PUT {{api}}/11 HTTP/1.1
Content-Type: application/json

{
    "nombre_usuario": "Yoru",
    "rut": "15.235.5432",
    "correo_electronico": "yoru@valorant.com",
    "direccion": "atlantico",
    "numero_cel": "97653297"
}