USE [master]
GO
/****** Object:  Database [GCC]    Script Date: 01-07-2021 0:32:44 ******/
CREATE DATABASE [GCC]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GCC', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.VINCESQLSERVER\MSSQL\DATA\GCC.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'GCC_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.VINCESQLSERVER\MSSQL\DATA\GCC_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [GCC] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GCC].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [GCC] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [GCC] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [GCC] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [GCC] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [GCC] SET ARITHABORT OFF 
GO
ALTER DATABASE [GCC] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [GCC] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [GCC] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [GCC] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [GCC] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [GCC] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [GCC] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [GCC] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [GCC] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [GCC] SET  ENABLE_BROKER 
GO
ALTER DATABASE [GCC] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [GCC] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [GCC] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [GCC] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [GCC] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [GCC] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [GCC] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [GCC] SET RECOVERY FULL 
GO
ALTER DATABASE [GCC] SET  MULTI_USER 
GO
ALTER DATABASE [GCC] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [GCC] SET DB_CHAINING OFF 
GO
ALTER DATABASE [GCC] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [GCC] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [GCC] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [GCC] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'GCC', N'ON'
GO
ALTER DATABASE [GCC] SET QUERY_STORE = OFF
GO
USE [GCC]
GO
/****** Object:  Table [dbo].[mascota]    Script Date: 01-07-2021 0:32:45 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[mascota](
	[id_mascota] [int] IDENTITY(1,1) NOT NULL,
	[nombre_mascota] [varchar](20) NOT NULL,
	[raza] [varchar](20) NOT NULL,
	[sexo_mascota] [varchar](10) NOT NULL,
	[edad] [int] NULL,
	[peso] [float] NULL,
	[codigo_chip] [varchar](50) NULL,
	[foto_mascota] [image] NULL,
	[idusuario] [int] NULL,
	[fecha_nacimiento] [date] NULL,
 CONSTRAINT [PK_mascota] PRIMARY KEY CLUSTERED 
(
	[id_mascota] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[servicio]    Script Date: 01-07-2021 0:32:45 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[servicio](
	[id_servicio] [int] IDENTITY(1,1) NOT NULL,
	[fecha_solicitud] [date] NULL,
	[hora_solicitud] [time](0) NULL,
	[direccion_usuario] [text] NOT NULL,
	[duracion_paseo] [varchar](20) NULL,
	[mascota] [varchar](20) NOT NULL,
	[agregado] [text] NULL,
	[tiposervicio] [int] NOT NULL,
	[idusuario] [int] NOT NULL,
 CONSTRAINT [PK_servicio] PRIMARY KEY CLUSTERED 
(
	[id_servicio] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[solicitud]    Script Date: 01-07-2021 0:32:45 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[solicitud](
	[id_solicitud] [int] IDENTITY(1,1) NOT NULL,
	[descripcion] [text] NOT NULL,
	[servicio_id] [int] NOT NULL,
 CONSTRAINT [PK_solicitud] PRIMARY KEY CLUSTERED 
(
	[id_solicitud] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tipo_servicio]    Script Date: 01-07-2021 0:32:45 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tipo_servicio](
	[id_tiposerv] [int] NOT NULL,
	[n_tipo_servicio] [varchar](25) NOT NULL,
 CONSTRAINT [PK_tipo_servicio] PRIMARY KEY CLUSTERED 
(
	[id_tiposerv] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tipo_usuario]    Script Date: 01-07-2021 0:32:45 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tipo_usuario](
	[id_tipousuario] [int] NOT NULL,
	[n_tipousuario] [varchar](20) NOT NULL,
 CONSTRAINT [PK_tipo_usuario] PRIMARY KEY CLUSTERED 
(
	[id_tipousuario] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[usuario]    Script Date: 01-07-2021 0:32:45 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[usuario](
	[id_usuario] [int] IDENTITY(1,1) NOT NULL,
	[nombre_usuario] [varchar](40) NOT NULL,
	[apellido_usuario] [varchar](40) NOT NULL,
	[clave_usuario] [varchar](20) NOT NULL,
	[rut] [varchar](12) NULL,
	[correo_electronico] [varchar](30) NOT NULL,
	[direccion] [text] NULL,
	[numero_cel] [bigint] NULL,
	[tipousuario] [int] NOT NULL,
	[foto_perfil] [image] NULL,
 CONSTRAINT [PK_usuario] PRIMARY KEY CLUSTERED 
(
	[id_usuario] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[servicio]  WITH CHECK ADD  CONSTRAINT [FK_servicio_tipo_servicio] FOREIGN KEY([tiposervicio])
REFERENCES [dbo].[tipo_servicio] ([id_tiposerv])
GO
ALTER TABLE [dbo].[servicio] CHECK CONSTRAINT [FK_servicio_tipo_servicio]
GO
ALTER TABLE [dbo].[solicitud]  WITH CHECK ADD  CONSTRAINT [FK_solicitud_servicio] FOREIGN KEY([servicio_id])
REFERENCES [dbo].[servicio] ([id_servicio])
GO
ALTER TABLE [dbo].[solicitud] CHECK CONSTRAINT [FK_solicitud_servicio]
GO
ALTER TABLE [dbo].[usuario]  WITH CHECK ADD  CONSTRAINT [FK_usuario_usuario] FOREIGN KEY([tipousuario])
REFERENCES [dbo].[tipo_usuario] ([id_tipousuario])
GO
ALTER TABLE [dbo].[usuario] CHECK CONSTRAINT [FK_usuario_usuario]
GO
USE [master]
GO
ALTER DATABASE [GCC] SET  READ_WRITE 
GO